baseURL: ""
languageCode: en-us
title: Demo hugo site
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello Stranger"
    Content: Welcome to my blog. Here you'll find a lot cool information about cool stuff
  socialIcons:
    - name: facebook
      url: "www.facebook.com"
    - name: Twitter
      url: "www.twitter.com"
    - name: Github
      url: "www.github.com"
  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
